# The api key, secret key, and canvas page name are required to get started
# Tunnel configuration is only needed if you are going to use the facebooker:tunnel Rake tasks
# Your callback url in Facebook should be set to http://public_host:public_port
# If you're building a Facebook connect site, 
#    change the value of set_asset_host_to_callback_url to false
# To develop for the new profile design, add the following key..
# api: new
# remove the key or set it to anything else to use the old facebook design.
# This should only be necessary until the final version of the new profile is released.

production:
  api_key: 800a4568f45c040653edc996283fc1db
  secret_key: eff1ddb39dca9185efb31669b69456f5
  canvas_page_name:
  callback_url: http://c2w.com/
  pretty_errors: true
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

staging:
  api_key: fe5c2ab869a418c6e51ed21a9f791eba
  secret_key: 79691b90b4a69144ebbf75e444a9788d
  canvas_page_name:
  callback_url: http://staging.c2w.com/
  pretty_errors: true
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

test:
  api_key: 
  secret_key: 
  canvas_page_name: 
  callback_url:
  set_asset_host_to_callback_url: false
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0

development:
  api_key: 2433a72739fae77447592d6544ec9e52
  secret_key: be0360bc8bb9dab57cfdc74ebe607f2e
  canvas_page_name: 
  callback_url: http://c2w.nikhilgupte.com
  set_asset_host_to_callback_url: false   
  tunnel:
    public_host_username: 
    public_host: 
    public_port: 4007
    local_port: 3000
    server_alive_interval: 0
